### ISSUE TITLE
Protractor fails: window.getAllAngularTestabilities is not a function

### ISSUE THREAD

**Issue by emcniece** [marcoturi/ionic2-boilerplate#15]
Fresh clone of master branch, Protractor fails with ChromeDriver on macOS 10.12.1:

```
➜  ionic2-boilerplate git:(master) ✗ npm run e2e

> ionic2-boilerplate@0.11.0 pree2e /Users/emcniece/Code/ionic/ionic2-boilerplate
> cd www && python -m SimpleHTTPServer 8090 >> ../python_serve.log 2>&1 &


> ionic2-boilerplate@0.11.0 e2e /Users/emcniece/Code/ionic/ionic2-boilerplate
> protractor

[15:25:22] I/direct - Using ChromeDriver directly...
[15:25:22] I/launcher - Running 1 instances of WebDriver
Started
Spec started
F
  App
    ✗ should have a title
      - Failed: Angular could not be found on the page http://localhost:8090/ : retries looking for angular exceeded
      - Failed: Error while waiting for Protractor to sync with the page: "window.getAllAngularTestabilities is not a function"



Failures:
1) App should have a title
  Message:
    Failed: Angular could not be found on the page http://localhost:8090/ : retries looking for angular exceeded
  Stack:
    Error: Angular could not be found on the page http://localhost:8090/ : retries looking for angular exceeded
        at /Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/protractor/built/browser.js:516:23
        at ManagedPromise.invokeCallback_ (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/selenium-webdriver/lib/promise.js:1379:14)
        at TaskQueue.execute_ (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/selenium-webdriver/lib/promise.js:2775:27)
        at /Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:103:7)
    From: Task: Run beforeEach in control flow
        at Object.<anonymous> (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/jasminewd2/index.js:79:14)
    From asynchronous test:
    Error
        at Suite.<anonymous> (/Users/emcniece/Code/ionic/ionic2-boilerplate/src/pages/home/home.e2e.ts:10:5)
        at Object.<anonymous> (/Users/emcniece/Code/ionic/ionic2-boilerplate/src/pages/home/home.e2e.ts:9:1)
        at Module._compile (module.js:556:32)
        at Module.m._compile (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/ts-node/src/index.ts:406:23)
        at Module._extensions..js (module.js:565:10)
        at Object.require.extensions.(anonymous function) [as .ts] (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/ts-node/src/index.ts:409:12)
  Message:
    Failed: Error while waiting for Protractor to sync with the page: "window.getAllAngularTestabilities is not a function"
  Stack:
    Error: Error while waiting for Protractor to sync with the page: "window.getAllAngularTestabilities is not a function"
        at /Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/protractor/built/browser.js:270:23
        at ManagedPromise.invokeCallback_ (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/selenium-webdriver/lib/promise.js:1379:14)
        at TaskQueue.execute_ (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/selenium-webdriver/lib/promise.js:2775:27)
        at /Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (internal/process/next_tick.js:103:7)Error
        at ElementArrayFinder.applyAction_ (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/protractor/built/element.js:403:27)
        at ElementArrayFinder._this.(anonymous function) [as isDisplayed] (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/protractor/built/element.js:101:30)
        at ElementFinder.(anonymous function) [as isDisplayed] (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/protractor/built/element.js:740:22)
        at Object.<anonymous> (/Users/emcniece/Code/ionic/ionic2-boilerplate/src/pages/home/home.e2e.ts:15:29)
        at /Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/jasminewd2/index.js:94:23
        at new ManagedPromise (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/selenium-webdriver/lib/promise.js:1082:7)
        at controlFlowExecute (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/jasminewd2/index.js:80:18)
        at TaskQueue.execute_ (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/selenium-webdriver/lib/promise.js:2896:21)
        at asyncRun (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/selenium-webdriver/lib/promise.js:2820:25)
    From: Task: Run it("should have a title") in control flow
        at Object.<anonymous> (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/jasminewd2/index.js:79:14)
        at /Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/jasminewd2/index.js:103:16
        at ManagedPromise.invokeCallback_ (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/selenium-webdriver/lib/promise.js:1379:14)
        at TaskQueue.execute_ (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/selenium-webdriver/lib/promise.js:2913:14)
        at TaskQueue.executeNext_ (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    From asynchronous test:
    Error
        at Suite.<anonymous> (/Users/emcniece/Code/ionic/ionic2-boilerplate/src/pages/home/home.e2e.ts:14:5)
        at Object.<anonymous> (/Users/emcniece/Code/ionic/ionic2-boilerplate/src/pages/home/home.e2e.ts:9:1)
        at Module._compile (module.js:556:32)
        at Module.m._compile (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/ts-node/src/index.ts:406:23)
        at Module._extensions..js (module.js:565:10)
        at Object.require.extensions.(anonymous function) [as .ts] (/Users/emcniece/Code/ionic/ionic2-boilerplate/node_modules/ts-node/src/index.ts:409:12)

1 spec, 1 failure
Finished in 10.671 seconds

**************************************************
*                    Failures                    *
**************************************************

1) App should have a title
  - Failed: Angular could not be found on the page http://localhost:8090/ : retries looking for angular exceeded
  - Failed: Error while waiting for Protractor to sync with the page: "window.getAllAngularTestabilities is not a function"

Executed 1 of 1 spec (1 FAILED) in 11 secs.
[15:25:33] I/launcher - 0 instance(s) of WebDriver still running
[15:25:33] I/launcher - chrome #01 failed 1 test(s)
[15:25:33] I/launcher - overall: 1 failed spec(s)
Closing report
[15:25:33] E/launcher - Process exited with error code 1

npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/emcniece/.nvm/versions/node/v6.7.0/bin/node" "/Users/emcniece/.nvm/versions/node/v6.7.0/bin/npm" "run" "e2e"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! ionic2-boilerplate@0.11.0 e2e: `protractor`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic2-boilerplate@0.11.0 e2e script 'protractor'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic2-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic2-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic2-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/emcniece/Code/ionic/ionic2-boilerplate/npm-debug.log
```

Investigation reveals that this may be related to Angular itself: https://github.com/angular/protractor/issues/3178

**Comment by marcoturi** [comment]
Did you made a build first ? Protractor is running through a tiny python server serving the www folder (to avoid not closed ports problems on repeated tests...). If you don't build at least one time your project www folder will be empty.

**Comment by emcniece** [comment]
Confirmed that building first still results in this error - good thought.

**Comment by emcniece** [comment]
The previously referenced issue was a red herring, but I'll leave the link for good measure.

One of the test instances crashed and the python SimpleServer hung and occupied :8090 - killing this process allowed `npm run e2e` to work as expected.

**Comment by marcoturi** [comment]
Unfortunately I'm not able to reproduce this issue. I tried:

```
rm -rf node_modules/ 
(cleaned www)
npm install
./node_modules/.bin/webdriver-manager update
npm run dev
(on second tab) npm run e2e
```

No errors on Mac OS El cap 10.11 with node 6.9.1
```

> ionic2-boilerplate@0.11.0 pree2e /Users/marco/Sources/Github/ionic2-boilerplate
> cd www && python -m SimpleHTTPServer 8090 >> ../python_serve.log 2>&1 &


> ionic2-boilerplate@0.11.0 e2e /Users/marco/Sources/Github/ionic2-boilerplate
> protractor

[00:41:07] I/direct - Using ChromeDriver directly...
[00:41:07] I/launcher - Running 1 instances of WebDriver
Started
Spec started
.
  App
    ✓ should have a title




1 spec, 0 failures
Finished in 1.944 seconds

Executed 1 of 1 spec SUCCESS in 2 secs.
[00:41:10] I/launcher - 0 instance(s) of WebDriver still running
[00:41:10] I/launcher - chrome #01 passed
Closing report

```
