### ISSUE TITLE
scss-lint fails

### ISSUE THREAD

**Issue by midemarc** [marcoturi/ionic2-boilerplate#31]
**What triggers the problem ?**
Running `scss-lint`

**What happens exactly ?**
```
npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/Cellar/node/7.7.4/bin/node" "/usr/local/bin/npm" "run" "scss-lint"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! ionic2-boilerplate@0.21.0 scss-lint: `scss-lint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic2-boilerplate@0.21.0 scss-lint script 'scss-lint'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic2-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scss-lint
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic2-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic2-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Marc/Development/IonicApps/ucrowd_app/npm-debug.log
```

**The log file in question :**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.7.4/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'scss-lint' ]
2 info using npm@4.1.2
3 info using node@v7.7.4
4 verbose run-script [ 'prescss-lint', 'scss-lint', 'postscss-lint' ]
5 info lifecycle ionic2-boilerplate@0.21.0~prescss-lint: ionic2-boilerplate@0.21.0
6 silly lifecycle ionic2-boilerplate@0.21.0~prescss-lint: no script for prescss-lint, continuing
7 info lifecycle ionic2-boilerplate@0.21.0~scss-lint: ionic2-boilerplate@0.21.0
8 verbose lifecycle ionic2-boilerplate@0.21.0~scss-lint: unsafe-perm in lifecycle true
9 verbose lifecycle ionic2-boilerplate@0.21.0~scss-lint: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Marc/Development/IonicApps/ucrowd_app/node_modules/.bin:/usr/local/opt/scala/idea:/Users/Marc/Library/Android/sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin
10 verbose lifecycle ionic2-boilerplate@0.21.0~scss-lint: CWD: /Users/Marc/Development/IonicApps/ucrowd_app
11 silly lifecycle ionic2-boilerplate@0.21.0~scss-lint: Args: [ '-c', 'scss-lint' ]
12 silly lifecycle ionic2-boilerplate@0.21.0~scss-lint: Returned: code: 1  signal: null
13 info lifecycle ionic2-boilerplate@0.21.0~scss-lint: Failed to exec scss-lint script
14 verbose stack Error: ionic2-boilerplate@0.21.0 scss-lint: `scss-lint`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ionic2-boilerplate@0.21.0
16 verbose cwd /Users/Marc/Development/IonicApps/ucrowd_app
17 error Darwin 13.4.0
18 error argv "/usr/local/Cellar/node/7.7.4/bin/node" "/usr/local/bin/npm" "run" "scss-lint"
19 error node v7.7.4
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error ionic2-boilerplate@0.21.0 scss-lint: `scss-lint`
22 error Exit status 1
23 error Failed at the ionic2-boilerplate@0.21.0 scss-lint script 'scss-lint'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ionic2-boilerplate package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     scss-lint
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ionic2-boilerplate
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ionic2-boilerplate
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Can you help me with that ? Can I do something else to explain the problem and context better ? Thanks in advance.

**Comment by marcoturi** [comment]
Have you installed ruby ? And run gem install scss_lint ?

**Comment by midemarc** [comment]
Yes I did. I didn't include it because I thaught it was irrelevant but I also get many warnings on the scss of assets and node_modules before the errors I posted :
```
www/assets/fonts/roboto.scss:26:237 [W] StringQuotes: Prefer single quoted strings
www/assets/fonts/roboto.scss:30:16 [W] StringQuotes: Prefer single quoted strings
www/assets/fonts/roboto.scss:33:14 [W] StringQuotes: Prefer single quoted strings
www/assets/fonts/roboto.scss:33:36 [W] StringQuotes: Prefer single quoted strings
www/assets/fonts/roboto.scss:33:105 [W] StringQuotes: Prefer single quoted strings
www/assets/fonts/roboto.scss:33:167 [W] StringQuotes: Prefer single quoted strings
www/assets/fonts/roboto.scss:33:227 [W] StringQuotes: Prefer single quoted strings
```

**Comment by marcoturi** [comment]
Those warnings are about sass linting (this means that scss-lint is working and you should simply fix those warnings and errors).

**Comment by midemarc** [comment]
Thank you very much ; I thought there was a problem since there were "only" warnings and it broke anyway.
I configure scss-lint to exclude node-modules and assets from the linting and discovered my own mistakes that were hidden in the mass of warnings…
Thank you for your patience.
